[package]
name = "satisfactory_serve_map"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rocket = "0.5"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
